export { default as AboutEducator } from './AboutEducator'
export { default as CtaAndContact } from './CtaAndContact'
export { default as Hero } from './Hero'
export { default as LearningEnvironment } from './LearningEnvironment'
export { default as Reviews } from './Reviews'
export { default as Subjects } from './Subjects'
export { default as WhyChooseUs } from './WhyChooseUs'
